name:                adn
version:             0.1.0.0
github:              "loltarudesh/adn-warp"
license:             BSD3
author:              "Lorbam Oltarudesh"
maintainer:          "lorbamOltarudesh@protonmail.com"
copyright:           "2021 Lorbam Oltarudesh"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis: Another Distributed Network
category: Network

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/loltarudesh/adn-warp#readme>

dependencies:
- base >= 4.7 && < 5
- array == 0.5.4.*
- containers >= 0.6.4 && < 0.6.6
- bytestring == 0.10.12.*
- binary == 0.8.8.*
- lens >= 4.19 && < 5.1
- mtl == 2.2.*
- network >= 3.1.1 && < 3.1.3
- split == 0.2.3.*
- utf8-string == 1.0.*
- exceptions == 0.10.4
- time == 1.9.3.*
- parsec == 3.1.14.*

# for timers 
- timers == 0.2.0.*
- suspend == 0.2.0.*

# for ADN.CLI
- haskeline == 0.8.2.*

# not all realy used: ADN.Core.Pipe.Chan 
- stm == 2.5.0.*   
- unagi-chan == 0.4.1.*

# for ADN.Tun
- unix == 2.7.2.* # manage system handler
- process == 1.6.13.* # call shell commands

# for argument parsing
- optparse-applicative == 0.16.1.*

library:
  source-dirs: src

executables:
  adn-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Widentities
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wpartial-fields
    - -Wredundant-constraints
    dependencies:
    - adn

